# Generated by Django 3.2.8 on 2021-10-22 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0003_auto_20211022_1524"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
    ]
