# Generated by Django 3.2.8 on 2021-10-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ')),
                ('address', models.CharField(blank=True, max_length=90, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('useres', models.ManyToManyField(related_name='_company_company_useres_+', to='company.Company')),
            ],
        ),
    ]
