# Generated by Django 3.2.8 on 2021-10-22 11:43

import company.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20211022_1143'),
        ('company', '0002_alter_company_useres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, validators=[company.validators.validate_CNPJ, company.validators.valida_cnpj], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='useres',
            field=models.ManyToManyField(to='register.Client'),
        ),
    ]
